Traceback (most recent call last):
  File "/share/apps/miniconda3/envs/sphinx/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/share/apps/miniconda3/envs/sphinx/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/share/apps/miniconda3/envs/sphinx/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/share/apps/miniconda3/envs/sphinx/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/share/apps/miniconda3/envs/sphinx/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/share/apps/miniconda3/envs/sphinx/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/share/apps/miniconda3/envs/sphinx/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/share/apps/miniconda3/envs/sphinx/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from qiskit_textbook.widgets import dj_widget
dj_widget(size="small", case="balanced")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-4e855ca33732>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mfrom[0m [0mqiskit_textbook[0m[0;34m.[0m[0mwidgets[0m [0;32mimport[0m [0mdj_widget[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mdj_widget[0m[0;34m([0m[0msize[0m[0;34m=[0m[0;34m"small"[0m[0;34m,[0m [0mcase[0m[0;34m=[0m[0;34m"balanced"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'qiskit_textbook'
ModuleNotFoundError: No module named 'qiskit_textbook'

